### ISSUE TITLE
Building ARM images ;)

### ISSUE THREAD

**Issue by rande** [ekino/docker-buildbox#621] opened 2021-11-25 23:54 UTC
Tasks

- [ ] check if modd and ci-helper work on arm. 
- [ ] found a clever way to pass the arch name into the Dockerfile so arch dependant binary can be used
- [ ] alert the client to use a new attribute platform (https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.build)
- [ ] define the list of platforms required, intel and arm, but we need to find the technical name
- [ ] adjust the matric ci to run the platform
- [ ] test each image with the new build

**Comment by Crow-EH** [comment] 2021-11-28 02:59
The correct way should be to build the image on multiple architecture using docker buildx, with one tag pointing to multiple arch, then letting docker pull the correct image depending on the user's architecture.

Buildx doc : https://docs.docker.com/buildx/working-with-buildx/

A blog post about it : https://www.docker.com/blog/multi-arch-images/

The issue is I don't think our current python lib docker-py sypports it.

**Comment by Crow-EH** [comment] 2021-12-01 18:51
Seems like we'll have to use the legacy way to build multiple architectures (one tag = one architecture) if we use our current lib docker-py : [It doesn't support BuildKit](https://github.com/docker/docker-py/issues/2230).

The lib allows to pass a platform when building but that's it : https://docker-py.readthedocs.io/en/stable/images.html


We could also switch to https://gabrieldemarmiesse.github.io/python-on-whales/, which sits on top of the docker installed on the OS instead of reimplementing it.

**Comment by rande** [comment] 2021-12-02 10:07
So, we need to remove the client call, to call the docker command directly using the build sub-command.

**Comment by ekinoben** [comment] 2021-12-07 13:19
I did a quick audit of our base images - see [buildbox-image-audit.20211207.xlsx](https://github.com/ekino/docker-buildbox/files/7668484/buildbox-image-audit.20211207.xlsx)

It looks like they all support multi-arch builds (at minimum, `amd64` & `arm64`, which I believe is sufficient for us?) except for box `react-native`, which is based on `openjdk:8u282-jdk-slim` and only supports `amd64`. 

That base image looks to be a bit out of date anyway. Later versions (e.g. `openjdk:18-jdk-slim`) support both `amd64` & `arm64` - can we update `react-native` to use this later base image? This would save us having to pass an ARCH arg into each Dockerfile, or use arch-specific Dockerfiles.

**Comment by Crow-EH** [comment] 2021-12-07 13:33
Great work @ekinoben !

I think we just need to make sure the android sdk is compatible with the version of java we use. I'll contact Ced and Lucas to get some info (I'll add you to the chat).

Maybe they don't use it anymore, idk.

Jjdk 18 would be too bleeding edge anyway, 11 or 17 would be my guess.

**Comment by Crow-EH** [comment] 2021-12-07 13:50
As seen with Lucas, Ced, and @ekinoben, the `react-native` image isn't used by ou mobile teams anymore (and isn't up to date anyway).

They switched to mobile-specific runners for build and deploy.

I'll create an issue to delete it.

**Comment by Crow-EH** [comment] 2021-12-08 18:02
@ekinoben `react-native` is no more :)

**Comment by ekinoben** [comment] 2021-12-16 16:56
Quick progress update: I've switched the Python build script to use python-on-whales / docker buildx, and successfully built some multi-arch images. I've also updated all the affected Dockerfiles to fetch architecture-specific dependencies, using the `TARGETARCH` env var that buildx populates (i.e. replaced hardcoded references to x86 / amd64).

I'm currently trying to solve the "how to test it" issue: buildx with a multi-arch image [won't give you a usable local image](https://github.com/docker/buildx/issues/166). It'll be in the build cache, but you can't run it, so we can't test it. As I see it, we could:

- add `--push` arg to `docker buildx build`. This will build _and push_ the image to the registry, which means pushing to the registry before testing it. Which sounds kind of bad.

- build for each arch individually, test locally (QEMU?) then combine via `docker manifest create` and push to registry. This kind of defeats the point of using buildx.

- build for each arch individually, test locally (QEMU?), then build for all arch's using buildx, and push to registry. This means building each image twice.

- build multi-arch locally via buildx, export as tar (i.e. `docker buildx build -o - - > image_name.tar`) and load it via `docker load` for testing. Then push the tar to the repo? Or... something.

Any thoughts on the above?

**Comment by Crow-EH** [comment] 2021-12-21 10:28
Hi @ekinoben, sorry for the delay.

I didn't know this issue, that's too bad.

IMO the most sensible option would be to use `docker manifest create`, which should work through python-on-whales, since it only build images once, test the images that we'll push, and just add on "merge" step. Too bad for buildx. :(

For testing, maybe we can keep the existing x86-64 tests right now, and think about a clean solution later ? That would allow M1 Mac users to use our arm images faster, give us some feebacks etc.

**Comment by axelpavageau** [comment] 2022-11-28 08:38
the most used images are now available for arm64. I'll close this meta issue and track the remaining work in dedicated issues : 

- #965
- #966 
- #967 
- #968 
- #969 
- #970 
- #971 
- #972

**Closed by axelpavageau** 2022-11-28 08:38 UTC
Labels: enhancement, docker
