### ISSUE TITLE
Switching tagging to Semantic Versioning

### ISSUE THREAD

**Issue by syphernl** [ekino/docker-buildbox#399] opened 2021-05-04 07:14 UTC
Would it be possible to switch the container tagging to use semantic versioning instead of the current `YYYY-MM-DD` setup? 
This makes possible for using tools like [Renovate](https://github.com/renovatebot/renovate) to update the container whenever there is a new release.

**Comment by rande** [comment] 2021-05-10 13:06
@syphernl thanks for opening this issue. We don't use semver because we don't need it. Each box has its own lifecycle, and we don't care about BC. If someone changes the tag version in a Gitlab pipeline, then he/she has to make sure the pipeline continue to work. Which is pretty straightforward, just open a PR, change the version, push, check and merge if ok. Does `renovate` allows to update GitLab definition to use a newer version?

We also don't recommend the usage of those boxes in a production system, this should only be used with GitlabCI.

**Comment by fpavageau** [comment] 2021-05-10 14:02
Simply using `YYYY.MM.DD` instead of `YYYY-MM-DD` might do the trick, it does look semversy.

**Comment by syphernl** [comment] 2021-05-10 14:22
> Simply using `YYYY.MM.DD` instead of `YYYY-MM-DD` might do the trick, it does look semversy.

Unfortunately it won't be as straight-forward as that:

- `2021.04.01` -> `2021.04.02` will be considered patch release
- `2021.04.01` -> `2021.05.01` will be considered minor release
- `2021.04.01` -> `2022.05.01` will be considered major release

For tagging I like tools like [semantic-release](https://github.com/semantic-release/semantic-release) to automatically determine the next tag based on the commit messages. 
For instance if it is prefixed with `fix:` will only bump the patch release number, prefixing with `feat:` will bump the minor release number. But unfortunately I don't think it will work (well) within a repo structure like this one where there are many sub-projects into a single repository.

**Comment by fpavageau** [comment] 2021-05-10 16:27
I know it won't magically be semver, but if it allows Renovate to pick up the changes because it matches the `x.y.z` pattern, that would be progress. Unless Renovate depends on the type of release?

It's going to be difficult to go beyond that, because as you note it's a single repository with multiple artifacts, and semver won't mean much across those: you make a breaking change in the Node image, so you change the major version, but there's probably no breaking change in the other images so it won't actually help you if you use the Python image.

**Comment by axelpavageau** [comment] 2021-07-23 12:29
> Simply using `YYYY.MM.DD` instead of `YYYY-MM-DD` might do the trick, it does look semversy.

I can confirm renovate handles `YYYY.MM.DD` properly

**Comment by axelpavageau** [comment] 2021-08-02 09:48
hello @syphernl. 

As my colleagues mentioned, we won't change to a "true" semver scheme, since it doesn't make sense for a multi-images monorepo like this.
However since we're already using a semver-ish syntax (`YYYY.MM.DD`) automated updates are handled correctly by Dependabot & Renovate. 

I'll close this issue, as we feel this is working as intended. 

Feel free to comment if we misunderstood your point.

**Closed by axelpavageau** 2021-08-02 09:48 UTC
